<?php
/** @var \Magento\Framework\View\Element\Template $block */

?>

<div class="container-auth">
    <ul class="nav justify-content-end sticky-top" >
            <li class="nav-item">
                <a href="#" class="nav-link"   aria-disabled="true">
                    <i class="auth__menu-ico"></i>
                </a>
            </li>
    </ul>
    <div class="logo-auth"><img src="<?php echo $this->getViewFileUrl('OmniPro_LuzBelkis::images/logo-auth.svg'); ?>" alt="logo_auth"></div>

    <div>
        <div class="auth__login-register mb-5" id="container-formAuth">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item login" role="presentation">
                    <a class="nav-link active" id="login-tab" data-bs-toggle="tab" href="#login" role="tab" aria-controls="login" aria-selected="true">
                        Ingreso
                    </a>
                </li>
                    <li class="nav-item register" role="presentation">
                        <a class="nav-link" id="register-tab" data-bs-toggle="tab" href="#register" role="tab" aria-controls="register" aria-selected="false">Registro</a>
                    </li>
                </ul>
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="login" role="tabpanel" aria-labelledby="login-tab">
                        <div>
                            <form autocomplete="off"> 
                                <div class="mb-3">
                                    <label for="email" class="form-label">Email</label>
                                    <input type="text" class="form-control input-custom" id="email" name="email" placeholder="ejemplo@email.com" autocomplete="off" value="">
                                </div>
                                <div class="mb-3">
                                    <label for="password" class="form-label">Contraseña</label>
                                    <input type="password" class="form-control input-custom" id="password" name="password" autocomplete="off" placeholder="******" value="">
                                </div>
                                <div class="form-check form-switch mb-4 mt-4">
                                    <div class="onoffswitch">
                                        <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" tabindex="0" checked>
                                        <label class="onoffswitch-label" for="myonoffswitch"></label>
                                    </div>
                                    <label class="form-check-label newsletter" for="flexSwitchCheckChecked">Suscribirse al Newsletter</label>
                                </div>
                                <div class="d-grid gap-2 col-12 mx-auto mb-3">
                                    <button class="btn btn-auth" type="submit">Ingreso</button>
                                </div>
                                <div class="form-check text-center">
                                    <a href="#" class="recover-password">Olvide Contraseña</a>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="register" role="tabpanel" aria-labelledby="register-tab">
                        <div>
                            <form autocomplete="off">
                                <div class="mb-3">
                                    <label for="name" class="form-label">Nombre</label>
                                    <input type="text" class="form-control input-custom" id="name" name="name" placeholder="Luz" autocomplete="off" value="">
                                </div>
                                <div class="mb-3">
                                    <label for="lastname" class="form-label">Apellido</label>
                                    <input type="text" class="form-control input-custom" id="lastname" name="lastname" placeholder="Fuentes" autocomplete="off" value="">
                                </div>
                                <div class="mb-3">
                                    <label for="email" class="form-label">Email</label>
                                    <input type="text" class="form-control input-custom" id="email_register" name="email" autocomplete="off" placeholder="ejemplo@email.com" value="">
                                </div>
                                    <div class="mb-4"><label for="password" class="form-label">Contraseña</label>
                                    <input type="password" class="form-control input-custom" id="password_register" name="password" placeholder="******" autocomplete="off" value="">
                                
                                </div>
                                 <div class="d-grid gap-2 col-12 mx-auto">
                                    <button class="btn btn-auth" type="submit">Registro</button>
                                 </div>
                            </form>
                        </div>
                    </div>
                </div>
        </div>

        <div id="mySidenav" class="sidenav-menu bg-menu">
            <div class="logo-auth"><img src="<?php echo $this->getViewFileUrl('OmniPro_LuzBelkis::images/logo-auth.svg'); ?>" alt="logo_auth"></div>
            <a href="#" class="closebtn">
                <i class="back-menu"></i>
            </a>
            <a href="void(0)" class="sidemenu-item">Inicio</a>
            <a href="void(0)" class="sidemenu-item">Servicio</a>
            <a href="void(0)" class="sidemenu-item">Nuestro Equipo</a>
            <a href="void(0)" class="sidemenu-item">Portafolio</a>
            <a href="void(0)" class="sidemenu-item">Contácto</a>
            <a href="void(0)" class="sidemenu-item">Términos y Condiciones</a>
        </div>
    </div>
</div>
