<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<h3><?= __("New blog post") ?></h3>
<form class="form" action="<?= $block->getUrl('pruebafrontend/bootcamp/save') ?>" method="post" data-hasrequired="* Required Fields" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field name required">
            <label for="titulo" class="label"><span>Titulo</span></label>
            <div class="control">
                <input type="text" id="titulo" name="titulo" placeholder="Titulo" class="input-text" data-validate='{"required":true}'>
            </div>
        </div>
        <div class="field name required">
            <label for="contenido" class="label"><span>Contenido</span></label>
            <div class="control">
                <input type="textarea" id="contenido" name="contenido" placeholder="contenido" class="input-text" data-validate='{"required":true}'>
            </div>
        </div>
        <div class="field name required">
            <label for="email" class="label"><span>Email</span></label>
            <div class="control">
                <input type="text" id="email" name="email" placeholder="email" class="input-text" data-validate='{"required":true}'>
            </div>
        </div>
        <div class="field name">
            <label for="img" class="label"><span>Img</span></label>
            <div class="control">
                <input type="text" id="img" name="img" placeholder="img" class="input-text">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
	        <div class="primary">
            		<input type="hidden" name="hideit" id="hideit" value="" />
            		<button type="submit" title="Submit" class="action submit primary">
                		<span>Submit</span>
            		</button>
        	</div>
    	</div>
</form>